/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDoctorRouteImport } from './routes/_authenticated/doctor'
import { Route as AuthenticatedStationRouteImport } from './routes/_authenticated/station'
import { Route as NurseActivateRouteImport } from './routes/nurse_.activate'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin/admins'
import { Route as AuthenticatedAdminHospitalsRouteImport } from './routes/_authenticated/admin/hospitals'
import { Route as AuthenticatedAdminPhysiciansRouteImport } from './routes/_authenticated/admin/physicians'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDoctorRoute = AuthenticatedDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStationRoute = AuthenticatedStationRouteImport.update({
  id: '/station',
  path: '/station',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const NurseActivateRoute = NurseActivateRouteImport.update({
  id: '/nurse_/activate',
  path: '/nurse/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHospitalsRoute =
  AuthenticatedAdminHospitalsRouteImport.update({
    id: '/hospitals',
    path: '/hospitals',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPhysiciansRoute =
  AuthenticatedAdminPhysiciansRouteImport.update({
    id: '/physicians',
    path: '/physicians',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nurse': typeof NurseRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/doctor': typeof AuthenticatedDoctorRoute
  '/station': typeof AuthenticatedStationRoute
  '/nurse/activate': typeof NurseActivateRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/hospitals': typeof AuthenticatedAdminHospitalsRoute
  '/admin/physicians': typeof AuthenticatedAdminPhysiciansRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/nurse': typeof NurseRoute
  '/doctor': typeof AuthenticatedDoctorRoute
  '/station': typeof AuthenticatedStationRoute
  '/nurse/activate': typeof NurseActivateRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/hospitals': typeof AuthenticatedAdminHospitalsRoute
  '/admin/physicians': typeof AuthenticatedAdminPhysiciansRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/nurse': typeof NurseRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/doctor': typeof AuthenticatedDoctorRoute
  '/_authenticated/station': typeof AuthenticatedStationRoute
  '/nurse_/activate': typeof NurseActivateRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/hospitals': typeof AuthenticatedAdminHospitalsRoute
  '/_authenticated/admin/physicians': typeof AuthenticatedAdminPhysiciansRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/nurse'
    | '/admin'
    | '/doctor'
    | '/station'
    | '/nurse/activate'
    | '/admin/admins'
    | '/admin/hospitals'
    | '/admin/physicians'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/nurse'
    | '/doctor'
    | '/station'
    | '/nurse/activate'
    | '/admin/admins'
    | '/admin/hospitals'
    | '/admin/physicians'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/nurse'
    | '/_authenticated/admin'
    | '/_authenticated/doctor'
    | '/_authenticated/station'
    | '/nurse_/activate'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/hospitals'
    | '/_authenticated/admin/physicians'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NurseRoute: typeof NurseRoute
  NurseActivateRoute: typeof NurseActivateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctor': {
      id: '/_authenticated/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AuthenticatedDoctorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/station': {
      id: '/_authenticated/station'
      path: '/station'
      fullPath: '/station'
      preLoaderRoute: typeof AuthenticatedStationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/nurse_/activate': {
      id: '/nurse_/activate'
      path: '/nurse/activate'
      fullPath: '/nurse/activate'
      preLoaderRoute: typeof NurseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hospitals': {
      id: '/_authenticated/admin/hospitals'
      path: '/hospitals'
      fullPath: '/admin/hospitals'
      preLoaderRoute: typeof AuthenticatedAdminHospitalsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/physicians': {
      id: '/_authenticated/admin/physicians'
      path: '/physicians'
      fullPath: '/admin/physicians'
      preLoaderRoute: typeof AuthenticatedAdminPhysiciansRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminHospitalsRoute: typeof AuthenticatedAdminHospitalsRoute
  AuthenticatedAdminPhysiciansRoute: typeof AuthenticatedAdminPhysiciansRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
    AuthenticatedAdminHospitalsRoute: AuthenticatedAdminHospitalsRoute,
    AuthenticatedAdminPhysiciansRoute: AuthenticatedAdminPhysiciansRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDoctorRoute: typeof AuthenticatedDoctorRoute
  AuthenticatedStationRoute: typeof AuthenticatedStationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDoctorRoute: AuthenticatedDoctorRoute,
  AuthenticatedStationRoute: AuthenticatedStationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NurseRoute: NurseRoute,
  NurseActivateRoute: NurseActivateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
